config/routes.rb
CrashCourse::Application.routes.draw do

  get "course/start_course"
  get "course/search"
  get "comment/index"
  get "comment/create"
  get "comment/new"
  get "comment/destroy"
  get "comment/show"
  get "course/create"
  get "course/new"
  get "course/get_user_learnings"
  get "course/get_user_teachings"
  get "course/show_user_course"
  get "course/browse"
  get "course/add"
  get "enrollment/add_one"
  get "enrollment/delete_one"
  get "enrollment/show_one"
  get "enrollment/show_all"
  get "comment/add_one"
  get "comment/edit_one"
  get "comment/delete_one"
  get "comment/show_one"
  get "comment/show_all"
  get "course/add_one"
  get "course/edit_one"
  get "course/delete_one"
  get "course/show_one"
  get "course/show_all"
  get "home/index"

  match '/browse_course', to:'course#show_all', via:'get'
  match '/course', to:'course#show_one', via:'get'
  match '/my_course', to:'course#show_user_course', via:'get'
  match '/teachings', to: 'course#get_user_teachings', via: 'get'
  match '/learnings', to: 'course#get_user_learnings', via: 'get'
  match '/add_course', to:'course#new', via:'get'
  match '/course/add_one', to:'course#create', via:'post'
  match '/search/result', to:'course#search', via:'get'
  match '/course/delete', to:'course#delete_one',via:'get'
  match '/start_course', to:'course#start_course',via:'get'
  
  match '/comment/new', to:'comment#new', via:'get'
  match '/course/create', to: 'comment#create', via:'post'
  
  match '/enrollment/add_one', to:'enrollment#add_one',via:'post'
  match '/enroll/delete', to:'enrollment#delete_one',via:'get'
  mount Forem::Engine, :at => '/forums'

  devise_for :users
  get "home/index"
  root :to => "home#index"

  

end

app/models/course.rb
class Course < ActiveRecord::Base
	TOPICS = ['Art','Science','Personal development','Home improvement','Others']
	belongs_to :teacher, :class_name => "User"
	has_many :enrollments, dependent: :destroy
	has_many :learners, :through=> :enrollments, :class_name => "User"
	has_many :comments, dependent: :destroy
	#attr_accessible :title, :topic, :length,:start_time,:description, :seats, :price,:attachment
	mount_uploader :attachment, AttachmentUploader
end

app/controllers/course_controller.rb
require 'active_support/all'
class CourseController < ApplicationController
  before_filter :authenticate_user!, :only => [:new,:create,:add,:add_one,:show_user_course]
  def new
    @course = Course.new
  end
  
  def create
    if params[:course][:title] == ''
      flash[:alert]="Title can NOT be empty!"
      redirect_to :back
    elsif params[:course][:topic] == ''
      flash[:alert]="Topic can NOT be empty!"
      redirect_to :back
    elsif params[:course][:seats].to_i <= 0
      flash[:alert]="Seats must be a positive integer!"
      redirect_to :back
    elsif params[:course][:length] == ''
      flash[:alert]="Length can NOT be empty!"
      redirect_to :back
    elsif params[:course][:price].to_i <= 0
      flash[:alert]="Price must be a positive integer!"
      redirect_to :back
    elsif params[:course]["start_time(1i)"] == '' ||params[:course]["start_time(2i)"] == ''||params[:course]["start_time(3i)"] == ''||params[:course]["start_time(4i)"] == ''||params[:course]["start_time(5i)"] == ''
      flash[:alert]="Time can NOT be empty!"
      redirect_to :back
    else
      course_start_time = DateTime.civil_from_format(:local,params[:course]["start_time(1i)"].to_i ,params[:course]["start_time(2i)"].to_i,params[:course]["start_time(3i)"].to_i,params[:course]["start_time(4i)"].to_i,params[:course]["start_time(5i)"].to_i).to_time
      if(course_start_time < DateTime.now.to_time)
        message = course_start_time.to_s + " is ealier than "+DateTime.now.to_time.to_s+" must pick a future time"
        flash[:alert]=message
        redirect_to :back
      else
        if get_availability?(course_start_time,params[:course][:length].to_i)      
          @course = Course.new (course_params)
          @course.user_id = current_user.id
          @course.save
          flash[:alert] = "Successfully created course."+course_start_time.to_s+" "+params[:course][:length]
          redirect_to({ :controller => :course, :action => :show_user_course }, :alert => "Successfully created course.")
        else
          flash[:alert] = "Time conflict! Please check 'My course'"
          redirect_to({ :controller => :course, :action => :show_user_course }, :alert => "Time conflict! Please double check")
        end
      end  
    end  
      
  end
  
  def add_one
    #if get_availability?(params[:start_time].to_time,params[:length].to_i)
      #Course.create(:title=>params[:title],:description=>params[:description],:length=>params[:length],:price=>params[:price],:attachment_path=>params[:attachment_path],:topic=>params[:topic],:seats=>params[:seats],:user_id=>current_user.id,:start_time=>params[:start_time].to_time)
      #render :json => {"response" => "Course added successfully" }
      @course = Course.new (course_params)
      @course.save
    #else
      #render :json => {"response" => "Time conflict! Please check 'My course' " }
    #end
    
  end

  def edit_one
  end

  def delete_one
    Course.destroy(params[:id])
    redirect_to :back
  end

  def show_user_course
    @page_user =  User.find_by(id:current_user.id)
    @user_teachings = Course.where("user_id = ?",current_user.id)
    @enrollments = {}

    @user_teachings.each do |teaching|
      @enrollments[teaching.id] = User.joins(:enrollments).where("enrollments.course_id=?",teaching.id)
    end
    @user_learnings = Course.joins(:enrollments).where("enrollments.user_id=?",current_user.id)
  end

  def show_one
    @course = Course.find(params[:id])
    @user = User.find(@course.user_id)
    @comments = Comment.where("course_id = ?", params[:id])
  end

  def browse
    @course = Course.where("start_time >= ? AND seats > 0", DateTime.now).all    
  end

  def show_all
    @courses = Course.where("start_time >= ? AND seats > 0", DateTime.now).all(:order=>params["Sort by"])
    #respond_to do |format|
    #  format.js { render :json => @course.to_json(:only => [:title, :id,:start_time])}
    #end
  end

  def search
    @search_results = Course.where("start_time >= ? AND seats > 0 And (title like ? or description like ?)", DateTime.now,"%#{params[:search]}%","%#{params[:search]}%").all(:order=>params["Sort by"])
  end

  private
  def course_params
    params.require(:course).permit(:title, :topic, :length,:start_time,:description, :seats, :price,:attachment)
  end




 
end

app/helpers/course_helper.rb
module CourseHelper
end

app/views/course/add.html.erb
<% content_for(:head) do %>
  <%= javascript_include_tag 'add_course.js' %>
<% end %>
 <!--<form class="form-horizontal" method="POST" > 
    <div class = "row">        
        <div class="span7">
        	<div class="control-group">
        		<label class="control-label">Title</label>
        		<div class="controls">
                    <input type="text" id="title" placeholder="Course Title">
                </div>
            </div>
       </div> 
       <div class="span5">
            <div class="control-group">
                <label class="control-label">Topic</label>
                <div class="controls">
                   <select id = "topic">
                        <option>Art</option>
                        <option>Science</option>
                        <option>Technology</option>
                        <option>Personal Improvement</option>
                        <option>Home Improvement</option>
                        <option>Recreation</option>
                        <option>Others</option>
                    </select>
                </div>
            </div>
       </div>      
   </div> 
   <div class="row">
         <div class="span7">
            <div class="control-group">
                <label class="control-label">Date</label>
                <div class="controls">
                    <select id = "month"  class="input-small">
                    </select>
                    /
                    <select id = "day"  class="input-small">
                    </select>
                    /
                    <select id = "year"  class="input-small">
                    </select>
                </div> 
            </div>         
        </div> 
        <div class = "span5">
            <div class="control-group">
                <label class="control-label">Time</label>
                <div class="controls">
                    
                        <select id = "time-hr"  class="input-small">
                        </select>
                        :
                        <select id = "time-min"  class="input-small">
                        </select>
                </div> 
            </div>
        </div>
    </div>  
    <div class = "row">
        <div class="span7">
            <div class="control-group">
                <label class="control-label">Length</label>
                <div class="controls">
                   <select id = "hour" class="input-small">
                        <option>0</option>
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>                       
                    </select>
                    hr
                    <select id = "minute" class="input-small">                     
                    </select>
                    min
                </div>
            </div>
       </div>      
        <div class="span5">
            <div class="control-group">
                <label class="control-label">Seats</label>
                <div class="controls">
                    <input type="text" id="seats" placeholder="seats">
                </div>
            </div>
       </div> 
   </div> 
   <div class = "row">
        <div class="span7">
           <div class="control-group">
                <label class="control-label" for="image-field">
                    Attachment
                </label>
                <div class="controls">
                    <input type="text" class="span4" placeholder="File name" id="image-file">
                    <button class="btn" id="upload-Attachment">Upload</button>
                    

                </div>
            </div>
        </div>
        <div class="span5">
            <div class="control-group">
                <label class="control-label">Price</label>
                <div class="controls">
                    <input type="text" id="price" placeholder="price">
                </div>
            </div>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">Description</label>
        <div class="controls">
           <textarea rows="6" 
                      id="description" 
                      class="span8 input-block-level"
                      placeholder="Course Description"></textarea>
        </div>
    </div>   
   
    
    <div class="control-group">
        <div class="controls">
            <input type= "submit" id="submit"  value="Submit" class="btn btn-primary"/>
        </div>    
    </div>    
</form>  -->         

<%= form_for @course,  :url => { :action => "add_one" },:html => {:multipart => true} do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :Title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :Topic %><br />
    <%= f.collection_select :topic, Course::TOPICS, :to_s, :to_s, 
       :include_blank => true%>
  </p>
  <p>
    <%= f.label :Time %><br />
    <%= f.datetime_select :start_time, { :include_blank => true, :start_year => 2013 } %>
  </p>
  <p>
    <%= f.label :Length %><br />
    <%= f.text_field :length %>
  </p>
  <p>
    <%= f.label :Description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.file_field :attachment %>
  </p>
  
  <p><%= f.submit %></p>
<% end %>

app/views/course/add_one.html.erb
<h1>Course#add_one</h1>
<p>Find me in app/views/course/add_one.html.erb</p>

app/views/course/browse.html.erb
<% content_for(:head) do %>
  <%= javascript_include_tag 'browse_course.js' %>
<% end %>

 <legend>Browse Course</legend>
     <div class="row">
        <div class="span2 offset10">
          <div class="dropdown">
              <button class="btn dropdown-toggle sr-only" type="button" id="dropdownMenu1" data-toggle="dropdown">
               Sort By 
               <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Date Added</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Topic</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Popularity</a></li>
      
              </ul>
             </div>

       </div>
   </div>
 
 <br /> <br />
 
<div id = "frame" class="row pagination-centered" >
  <%@course.each do |teaching|%>
    <ul class="thumbnails">
        <li class="span3">
            <a href="/course/?id=<%=@course.id%>" class="thumbnail">
                <img src="<%=@course.attachment_url%>" alt="" class="img-rounded" >
                <strong><%=@course.title%></strong>
            </a>
        </li>
    </ul>
  <% end %>

</div>

app/views/course/create.html.erb
<h1>Course#create</h1>
<p>Find me in app/views/course/create.html.erb</p>

app/views/course/delete_one.html.erb
<h1>Course#delete_one</h1>
<p>Find me in app/views/course/delete_one.html.erb</p>

app/views/course/edit_one.html.erb
<h1>Course#edit_one</h1>
<p>Find me in app/views/course/edit_one.html.erb</p>

app/views/course/get_user_learnings.html.erb
<h1>Course#get_user_learnings</h1>
<p>Find me in app/views/course/get_user_learnings.html.erb</p>

app/views/course/get_user_teachings.html.erb
<h1>Course#get_user_teachings</h1>
<p>Find me in app/views/course/get_user_teachings.html.erb</p>

app/views/course/new.html.erb
<% if flash[:alert] %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong><%= flash[:alert] %></strong>
    </div>
<% end %>
<%= form_for @course,  :url => { :action => "add_one" },:html => {:multipart => true} do |f| %>
  <%= f.hidden_field :user_id %>
  <legend>Add Course</legend>
  <div class = "row">
    <div class = "span6">
      <%= f.label :Title %>
      <%= f.text_field :title %>
    </div>  
    <div class = "span6">
      <%= f.label :Topic %>
      <%= f.collection_select :topic, Course::TOPICS, :to_s, :to_s, 
         :include_blank => true%>
    </div>     
  </div>
  <p>
    <%= f.label :Time %>
    <%= f.datetime_select :start_time, { :include_blank => true, :start_year => 2013}, :class=>"input-small" %>
  </p>
  
  <div class = "row">
    <div class = "span6">
      <%= f.label :Length %>
      <%= f.select :length, [['1','1'],['2','2'],['3','3']], { :include_blank => true} %>
    </div>
    <div class = "span6">
      <%= f.label :Image %>
      <%= f.file_field :attachment %>
    </div>
  </div>

  <div class = "row">
    <div class = "span6">
      <%= f.label :Seats %>
      <%= f.text_field :seats %>
    </div>
    <div class = "span6">
      <%= f.label :Price %>
      <%= f.text_field :price %>
    </div>
  </div>
  
  <p>
    <%= f.label :Description %>
    <%= f.text_area :description, :class => "span8", :rows => "10"%>
  </p>
  
  
  <p><%= f.submit "Submit", :class =>"btn btn-primary"%></p>
<% end %>

app/views/course/search.html.erb
<% content_for(:head) do %>
  <%= stylesheet_link_tag 'show_all.css' %>
<% end %>
<legend>Search result</legend>
     <div class="row">
        <div class="span4 offset8">
           <%= form_tag search_result_path, :method => 'get',:html=>{:id=>'sort_by'} do %>      <%="Sort by:"%>   
                <%= hidden_field_tag :search, params[:search] %>              
                <%= select_tag "Sort by",options_for_select([['Topic','topic'],['Start time','start_time'],['Seats','seats'],['Price','price']],:selected => params["Sort by"]), :include_blank => true,:onchange=> "this.form.submit();" %>                         
            <% end %>
         </div>
     </div>
 
 
 <br /> <br />
 
<div id = "frame" class="row pagination-centered" >
  <%@search_results.each do |course|%>
    <div class="span4">
      <ul class="thumbnails">
          <li class="span3">
              <div class="thumbnail"><a href="/course/?id=<%=course.id%>">

                <% if course.attachment_url==nil%>
                  <img src="/images/sample.jpg">
                <%else%>  
                    <img src="<%=course.attachment_url%>" alt="" class="img-rounded" >
                  <% end %>
                  <strong><%=course.title%></strong>
              </a></div>
          </li>
      </ul>
    </div>
  <% end %>

</div>

app/views/course/show_all.html.erb
 <legend>Browse Course</legend>
     <div class="row">
        <div class="span2 offset10">
          <div class="dropdown">
              <button class="btn dropdown-toggle sr-only" type="button" id="dropdownMenu1" data-toggle="dropdown">
               Sort By 
               <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Date Added</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Topic</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Popularity</a></li>
      
              </ul>
             </div>

       </div>
   </div>
 
 <br /> <br />
 
<div id = "frame" class="row pagination-centered" >
  <%@courses.each do |course|%>
    <div class="span4">
      <ul class="thumbnails">
          <li class="span3">
              <div class="thumbnail"><a href="/course/?id=<%=course.id%>">

                <% if course.attachment_url==nil%>
                  <img src="/images/sample.jpg">
                <%else%>  
                    <img src="<%=course.attachment_url%>" alt="" class="img-rounded" >
                  <% end %>
                  <strong><%=course.title%></strong>
              </a></div>
          </li>
      </ul>
    </div>
  <% end %>

</div>

app/views/course/show_one.html.erb
<% content_for(:head) do %>
  <%= javascript_include_tag 'enroll_course.js' %>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-info">
    	<button type="button" class="close" data-dismiss="alert">&times;</button>
    	<strong><%= flash[:alert] %></strong>
    </div>
<% end %>

<legend id = <%=@course.id%> ><%=@course.title%></legend>

<div class="media">
	<a class="pull-right" href="#">
		<%=image_tag @course.attachment_url,:width => 200, :height => 200%>
	</a>
	<div class="media-body">
		<i class="icon-user"></i><strong> <%=@user.username%></strong><br />
		<i class="icon-time"></i>

		<strong id = "time" data-start="<%=@course.start_time%>" data-length=<%=@course.length%>> 
		<%=@course.start_time.to_date%>
		<%=@course.start_time.to_time.strftime('%H:%M')%>~
		<%=(@course.start_time+@course.length.to_i*60.minutes).to_time.strftime('%H:%M')%></strong>

		<p>Seats left: <%=@course.seats%></p>
		<p><%= simple_format(@course.description) %></p>

	</div>	
</div>	
<br /><br/>
<div class="row">
	<div class = "span2 offset10">
		 <!--<input type= "submit" id="enroll"  value="Enroll" class="btn btn-large btn-primary"/>-->
			<%= button_to 'Enroll',{:controller => :enrollment, :action => 'add_one', :course_id => @course.id},:method=>:post, :class => "btn btn-large btn-primary" %>
		
	</div>
</div>
<% if @comments.count > 0%>
	<legend><%=@comments.count%> comments </legend>
	<%@comments.each do |comment|%>
		<i class="icon-user"></i>
		<strong> <%=(User.find(comment.user_id.to_s)).username %></strong><br />
		<%= simple_format(comment.content) %>
		<hr />
	<%end%>
<%end%>		

<%= render :template=>'comment/new',  :locals => {:@comment => Comment.new} %>

app/views/course/show_user_course.html.erb
<% content_for(:head) do %>
  <%= javascript_include_tag 'start_course.js' %>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-info">
    	<button type="button" class="close" data-dismiss="alert">&times;</button>
    	<strong><%= flash[:alert] %></strong>
    </div>
<% end %>
<strong class = "pull-right">Available credits: <%=@page_user.credit%></strong>
<legend>My Teachings</legend>

<table class="table table-condensed">
	<thead>
		<tr>
			<th>Course name</th>
			<th>Time</th>
			<th>Enrollments</th>
			<th>Status</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody id="teaching">
		<% if @user_teachings.count > 0%>
			<%@user_teachings.each do |teaching|%>
				<% end_time = teaching.start_time+teaching.length*60.to_i.minutes %>
				<tr>
					<td><a href = "/course?id=<%=teaching.id%>"><%=teaching.title%></a></td>
					<td><%=teaching.start_time.to_date%>
						<%=teaching.start_time.to_time.strftime('%H:%M')%>~
						<%=end_time.to_time.strftime('%H:%M')%></td>
					<td>
						<div class="accordion" id="accordion<%=teaching.id%>">
							<div class="accordion-group">
							<div class="accordion-heading">
								<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion<%=teaching.id%>" href="#collapseOne<%=teaching.id%>">
								<%=@enrollments[teaching.id].count%>
								</a>
							</div>
							<div id="collapseOne<%=teaching.id%>" class="accordion-body collapse">
								<div class="accordion-inner">
									<%@enrollments[teaching.id].each do |enrollment|%>
										<p><%=enrollment.email%><p>
									<%end%>
								</div>
							</div>
							</div>							
						</div>
					</td>	

					<%if DateTime.now > end_time %>
						<td>Expired</td>
						<td><button id= "delete-teaching" data-course-id=<%= teaching.id%> data-course-title=<%= teaching.title%>  data-toggle="modal" data-target="#teachModal<%=teaching.id%>" class="close pull-left">&times;</button></td>
					<% elsif DateTime.now < teaching.start_time %>
						<td>Scheduled</td><td><button id= "delete-teaching" data-course-id=<%= teaching.id%> data-course-title=<%= teaching.title%>  data-toggle="modal" data-target="#teachModal<%=teaching.id%>" class="close pull-left">&times;</button></td>
					<% else %>
						<td>In Process</td>
						<td><a class="btn" id="start" href="">Start</a><td>
					<% end %>  
					
				</tr>
				<div id="teachModal<%=teaching.id%>" class="modal hide fade">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<br />
					</div>
					<div id="teachModalBody" class="modal-body">
						<p>Do you really want to delete "<%=teaching.title%>"?</p>
					</div>
					<div class="modal-footer">
						<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
						<a href="/course/delete/?id=<%=teaching.id%>" class="btn btn-primary">Confirm</a>
					</div>
				</div>
				
			<% end %>
		<%else%>
			<tr>
				<td>none</td>
				<td></td>
				<td></td>
				<td></td>
			</tr>	
		<%end%>	
	</tbody>
</table>

<legend>My Learnings</legend>
<table class="table table-condensed">
	<thead>
		<tr>
			<th>Course name</th>
			<th>Time</th>
			<th>Status</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody id="learning">
		<% if @user_learnings.count > 0%>
			<%@user_learnings.each do |learning|%>
				<% end_time = learning.start_time+learning.length*60.to_i.minutes %>
				<tr>
					<td><a href = "/course?id=<%=learning.id%>"><%=learning.title%></a></td>
					<td><%=learning.start_time.to_date%>
						<%=learning.start_time.to_time.strftime('%H:%M')%>~
						<%=end_time.to_time.strftime('%H:%M')%></td>
					<%if DateTime.now > end_time %>
						<td>Expired</td>
					<% elsif DateTime.now < learning.start_time %>
						<td>Scheduled</td><td><button id= "delete-learning" data-learning=<%=learning.id%> data-toggle="modal" data-target="#learnModal<%=learning.id%>" class="close pull-left">&times;</button></td>
					<% else %>
						<td>In Process</td>
					<% end %>  
				</tr>

				<div id="learnModal<%=learning.id%>" class="modal hide fade">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<br />
					</div>
					<div id="learnModalBody" class="modal-body">
						<p>Do you really want to drop "<%=learning.title%>"?</p>
					</div>
					<div class="modal-footer">
						<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
						<a href="/enroll/delete/?course_id=<%=learning.id%>" class="btn btn-primary">Confirm</a>
					</div>
				</div>
					
			<% end %>
		<%else%>
			<tr>
				<td>none</td>
				<td></td>
				<td></td>
				<td></td>
			</tr>	
		<%end%>	
	</tbody>
</table>

app/views/course/start_course.html.erb
  <a class="btn btn-large btn-info" href="https://hangoutsapi.talkgadget.google.com/hangouts/_?gid=intense-acrobat-420">Go to Google Hangout for course!</a>